### ISSUE TITLE
App with Phonegap get different fingerprint every time 

### ISSUE THREAD

**Issue by igorosabel** [jackspirou/clientjs#1]
Hi!

I'm making an app for iPhone using Phonegap and I liked your library so I wanted to use it to identify people and remember their logins.

The problem is that every time I run the app it gets me different fingerprints. I haven't done anything weird, on XCode I run the app and gives me a value. I stop it, run it again and it gives me a different value.

Thanks!

**Comment by jackspirou** [comment]
@dunedain thanks for bringing up this issue!
