### ISSUE TITLE
what is the release status?

### ISSUE THREAD

**Issue by cekvenich** [jackspirou/clientjs#101]
Git release shows version 0.1.5 and npm shows 0.1.11: 4 years ago.

Can you do another release please? And maybe pick npm or git as release. If you do both then they should match.

**Comment by cekvenich** [comment]
This is the latest released version: https://cdn.jsdelivr.net/npm/clientjs@0.1.11/dist/client.min.js

**Comment by BendingBender** [comment]
The new release is out: https://github.com/jackspirou/clientjs/releases/tag/v0.2.0.
