### ISSUE TITLE
getsystemlanguage doesn't work for me

### ISSUE THREAD

**Issue by BarbzYHOOL** [jackspirou/clientjs#105]
getSystemLanguage() is not working for me, at all (i'm on linux ubuntu)

even on the demo page http://clientjs.org/ it says

`Your Result:` and it's empty

sad :(

**Comment by BendingBender** [comment]
This is fixed in the current master version.

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0). Feel free to reopen this ticket if you still have problems.
