### ISSUE TITLE
Device detecting doesn't work anymore

### ISSUE THREAD

**Issue by kgkg** [jackspirou/clientjs#106]
Hello,

all device related fields are undefined on both Desktop and Mobile devices.

It's probably because of using outdated ua-parser-js library - 0.7.10 is used while current version is 0.7.21.

Tried it with new version of ua-parser-js and things like uaParser.getDevice().model works without any issues there.

Can you please update ua-parser-js and rebuild this great library?

**Comment by akram71093** [comment]
Will this issue be fixed ? @kgkg did you find any other alternative ?

**Comment by kgkg** [comment]
@akram71093 I "fixed" this installing newest version of UaParser and initialize it before ClientJs initialization, since ClientJs uses window.UAParser variable.

`
window.UAParser = UaParser; // required for clientJs to use newer client
const clientJs = new ClientJS();
// now clientJs uses our installed version of UaParser
`

**Comment by gmerabishvili** [comment]
@kgkg  @akram71093 Any news about this issue? I couldn't make it work : (

**Comment by gmerabishvili** [comment]
Currently these properties are undefined: 
`cpu: undefined
device: undefined
deviceType: undefined
deviceVendor: undefined
systemLanguage: undefined`
