### ISSUE TITLE
Tutorial for all users which wants to use ClientJs in Angular

### ISSUE THREAD

**Issue by Lavos96** [jackspirou/clientjs#111]
Hi guys, i experienced some troubles with running this lib in Angular project. Despite that I managed to run this lib. I want to give you guys, some tutorial on how you can do that.
1. Firstly you need to download clientJs via npm: `npm install clientjs`
Unfortunately when you try to import this lib like this: `import ClientJS from 'clientjs'` you will get error in browser. This is the error:

> TypeError: 'arguments', 'callee' and 'caller' are restricted function properties and cannot be accessed in this context

2. In order to get rid off this error you will need to go to node_modules/clientjs/dist/client.min.js, you will need to get the content of this file then copy it on some of unminify websides and get rid off all arguments.callee in code. (you can follow this tutorial [stackoverflow-arguments-callee](https://stackoverflow.com/questions/12050183/javascript-arguments-callee-what-is-it-for) Or you can download this file from my repo [clientjs_without_arguments_callee](https://github.com/Lavos96/clientjs_without_arguments_callee))
When you do that copy back changed code to client.min.js.
3. In .ts file you now need to do import like that: `import 'clientjs'`
4. Then you can create clientJs object like this:
```
// @ts-ignore
const client = new ClientJS();
```
YOU CANT OMIT //@ts-ignore
5. Voila, from now you can use ClientJS in Angular project!

**Comment by palmersu** [comment]
Thank you for this detail, it helped me tremendously using this with Angular 10.  I wanted to add a couple notes on some additonal steps we took.

We use automated builds and we don't have the node_modules stored in source control so replacing the client.min.js file didn't work for out build / deploy process.  I used patch-package to account for this (https://www.npmjs.com/package/patch-package)

So the process we followed ended up being -->
1.) Follow the first 5 steps in Lavos96's post
2.) Upgrade ua-parser to the current version - this is thank you to the issue 106 (https://github.com/jackspirou/clientjs/issues/106).  We did this by replacing the file \node_modules\clientjs\src\vendor\ua-parser.js with the current file at https://github.com/faisalman/ua-parser-js/tree/master/src
3.) Install patch-package (npm install patch-package)
4.) Create the patch (npx patch-package clientjs)

This is working perfectly in Angular 10 now.  Thank you to Lavos and kgkg for your posts!
