### ISSUE TITLE
client.getBrowserData is not a function

### ISSUE THREAD

**Issue by chintan-banknovo** [jackspirou/clientjs#120]
I have installed using npm and imported in my js. 
import ClienJS from "clinetjs
const client = new ClientJS();
const ua = client.getBrowserData().ua
Also when I print client object it has only a few methods which are
client:: 
![image](https://user-images.githubusercontent.com/83203962/116854464-537e2a00-ac15-11eb-86dd-49bcb196dd8a.png)
Any particular reason I do not see all methods? 
Am I missing anything from a configuration perspective?

**Comment by BendingBender** [comment]
This is due to broken bundling. This is a known issue with the released version. Try to install clientjs from master:
```sh
npm install https://github.com/jackspirou/clientjs.git#master
```

**Comment by PoofyFoopy** [comment]
> This is due to broken bundling. This is a known issue with the released version. Try to install clientjs from master:
> ```sh
> npm install https://github.com/jackspirou/clientjs.git#master
> ```

Is there a reason as to why no new releases are being made?

**Comment by BendingBender** [comment]
Not really, it's just although I have collaborator-level access to this repo, only @jackspirou can make a release on npm.

**Comment by BendingBender** [comment]
@PoofyFoopy did it work for you?

**Comment by PoofyFoopy** [comment]
@BendingBender not yet tried, but planning to soon

**Comment by ekuzu** [comment]
If i install directly from master branch I started to getting ,
**Uncaught TypeError: ClientJS is not a constructor
    at eval (main.js?56d7:153)**

**Comment by BendingBender** [comment]
@ekuzu Would you mind sharing your code with us? How do you include this lib?

**Comment by ekuzu** [comment]
> @ekuzu Would you mind sharing your code with us? How do you include this lib?

```
const ClientJS = require('clientjs')
const client = new ClientJS()
Vue.prototype.$client = client
```

**Comment by BendingBender** [comment]
As you see in the example in the readme, the correct way to include this lib is:
```js
// or in a CommonJS environment:
var client = require('clientjs').ClientJS;
```

**Comment by BendingBender** [comment]
Ok, just noticed that there was a small issue with the example, still, my example from above should work.

**Comment by aok-dev** [comment]
Ran into this issue also.  @BendingBender suggesting is what eventually fixed it, tho I should say - console.log isn't a good indication.  After installing directly from master, logging out the main client function showed only 4 methods available, but calling .getFingerprint() on it worked just fine.  Also:  here's an ES6-y way to import/use:

`import { ClientJS} from 'clientjs';
let client = new ClientJS();
let fingerprint = client.getFingerprint();
`

Hoping that will help someone else.

**Comment by BendingBender** [comment]
@aok-dev Added the ES6 import example to readme,

**Comment by BendingBender** [comment]
Fixed in https://github.com/jackspirou/clientjs/releases/tag/v0.2.0
