### ISSUE TITLE
Compatibility problem with Vue

### ISSUE THREAD

**Issue by GiuseppeM92** [jackspirou/clientjs#127]
Hi,

I found a problem while implementing the library in Vue.

Downloading the version v.0.1.11, the exposed method are less, and for example the method **getFingerprint()** is not exposed.

This is how I included the library

import ClientJs from 'clientjs';
...
let clientJs = new ClientJs();
console.log(clientJs.getFingerprint());

generate error: Uncaught TypeError: clientJs.getFingerprint is not a function.

Many thanks

**Comment by BendingBender** [comment]
This is fixed in current master. Sadly, I can't publish to npm myself, although I have commit rights to this repo. So as a workaround you could depend directly on the version from github instead of the one from npm.

**Comment by jackspirou** [comment]
@BendingBender - I've added you to the npm registry

**Comment by BendingBender** [comment]
Thank you :pray:
