### ISSUE TITLE
Vulnerable ua-parser-js version

### ISSUE THREAD

**Issue by hom3chuk** [jackspirou/clientjs#130]
There's a malicious ua-parser-js NPM takeover, this PR bumps ua-parser-js version to the safe 0.7.30.

Security advisory: https://github.com/advisories/GHSA-pjwm-rvh2-c87w
GH thread: faisalman/ua-parser-js#536

PR: https://github.com/jackspirou/clientjs/pull/129

**Comment by BendingBender** [comment]
Thank you, @hom3chuk
