### ISSUE TITLE
Ubuntu font bug

### ISSUE THREAD

**Issue by damonsson** [jackspirou/clientjs#14]
I don't analyze why, but on some servers fingerprint id is different for SAME browser. Problem is Ubuntu font in function getFonts, sometimes was added to existing fonts, sometimes not. Please remove this font.

**Comment by jackspirou** [comment]
What do you think of the new `getCustomFingerprint` method?  Would it solve your need by removing Ubuntu fonts?  Or maybe you could parse out the particular font your having an issue with? 

`getCustomFingerprint` takes any number of data points you could pass to it as strings. It will even take data points outside of what ClientJS makes available.

You can find it here: http://clientjs.jacks.io/#Fingerprint-getCustomFingerprint

Let me know what you think.

**Comment by jackspirou** [comment]
@damonsson any thoughts?

**Comment by damonsson** [comment]
Sorry for long no response. New method is nice feature, but not solve problem if I want compare fonts to generated id. 
I have 2 VPS and 1 local server. When I test getFingerprint on Your demo site, localhost and 1 VPS- on all this site I have same Fingerprint ID, but on 2 VPS (same distibution as 1 VPS Ubuntu 14.04.3 LTS) I have different id. I debug why, and I saw that on 2 VPS I have "Ubuntu" in own fonts from getFonts(). 
I have no idea why, probably that is server configuration problem, but configuration is default.
So if You don't need use and compare fingerprint id between multiple servers all workings good. 
I think that good solution to this bug, will be add to documentation info about this possibility or remove "Ubuntu" from fontArray in getFonts().

**Comment by jackspirou** [comment]
So after a little googling it looks like `Ubuntu` is a valid font family http://font.ubuntu.com/ and others host it as a font as well http://www.fontsquirrel.com/fonts/ubuntu.

From what you see on your end is it fair to say the `Ubuntu` font the same font above?

If so I think we add documentation as you suggested.  Very strange for it to be erratically installed from the same Ubuntu 14.04.3 LTS.  Maybe it was different distribution images?

**Comment by damonsson** [comment]
I'm not sure about distribution images, because I don't have all privileges to VPS. Yes I think a some info in documentation will be helpful for another in feature with same problem. 

Please check 
1. Your demo site (font Ubuntu not exist- that is real behavior)
2. VPS - http://bit.ly/1OjLQpj (font Ubuntu not exist- that is real behavior)
3. VPS - http://bit.ly/1IlbeJ1 (font Ubuntu surprising exist [BUG]) (fingerprint will be same, because I customize function by removing Ubuntu from fontArray)

Code to console: 
```javascript
var client = new ClientJS();
var font = "Ubuntu";
var isFont = client.isFont(font);
console.log(isFont);
```

**Comment by jackspirou** [comment]
@damonsson thanks for the live examples, very helpful.  

So after taking a look and running the code you provided in the console I can reproduce the issue.  Also when I run `client.getFonts()` I get a list of fonts that don't contain the font `Ubuntu`, yet your code still returns true for that one site. I don't know yet exactly what is going on, but there must be some difference between both sites.  I'll see if I can find something to explain this behavior. 

Thanks again for following up on this issue as we debug it.

**Comment by jackspirou** [comment]
@damonsson after thinking I was losing my mind for a bit, I found the issue and it was pretty obvious!

http://bit.ly/1IlbeJ1 is loading the `Ubuntu` font into the browser from google fonts :sweat_smile: 

Line 15 of your source has: 
```HTML
<link href='//fonts.googleapis.com/css?family=Ubuntu:100,300,400,500,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
```

If you don't want Ubuntu to show up as a font, don't load `Ubuntu` from google fonts :)

It does bring up an interesting question around fonts loaded via a page vs fonts installed on a machine.  Not sure how that detection would work.  If you think this is a feature that is needed or something we should look into please open a different issue.  

Hope that helps!
