### ISSUE TITLE
Clientjs is showing same fingerprint for two different systems

### ISSUE THREAD

**Issue by muhammad009** [jackspirou/clientjs#15]
Clientjs library is showing same fingerprint IDs for two different systems connected on same network. How could I resolve this issue?

**Comment by jackspirou** [comment]
Hi @muhammad009, is the browser used on both systems the same, including the version?  Any details you can provide would be helpful, also the network is not taken into account when generating the IDs.

**Comment by muhammad009** [comment]
Hi jack, I have checked the following parameters on both systems. All of these have identical values.
* Available Resolution : 1366x728
* Browser : Chrome
* Browser Version: 46.0.2490.86
* Color Depth : 24
* CPU : amd64
* Current Resolution : 1366x768
* Engine : WebKit
* Engine Version : 537.36
* Flash Version : 19.0.0
* Fonts : Adobe Fangsong Std, Adobe Hebrew, Adobe Ming Std, Agency FB, Aharoni, Andalus,Angsana New, AngsanaUPC, Aparajita, Arabic Typesetting, Arial Black, Arial, Batang, BatangChe,  Bauhaus 93, Bell MT, Bodoni MT, Bookman Old Style, Broadway, Browallia New, BrowalliaUPC,  Calibri Light, Calibri, Californian FB, Cambria Math, Cambria, Candara, Castellar, Centaur, Century Gothic, Colonna MT, Comic Sans MS, Consolas, Constantia, Copperplate Gothic Light, Corbel, Cordia New, CordiaUPC, Courier New, DFKai-SB, DaunPenh, David, DilleniaUPC, DokChampa, Dotum, DotumChe, Ebrima, Engravers MT, Estrangelo Edessa, EucrosiaUPC, Euphemia, FangSong, Forte, FrankRuehl, Franklin Gothic Heavy, Franklin Gothic Medium, FreesiaUPC, French Script MT, Gabriola, Gautami, Georgia, Gigi, Gisha, Goudy Old Style, Gulim, GulimChe, Gungsuh, GungsuhChe, Haettenschweiler, Harrington, Impact, Informal Roman, IrisUPC, Iskoola Pota, JasmineUPC, KaiTi, Kalinga, Kartika, Khmer UI, KodchiangUPC, Kokila, Kozuka Gothic Pr6N, Lao UI, Latha, Leelawadee, Levenim MT, LilyUPC, Lucida Bright, Lucida Console, Lucida Fax, Lucida Sans Unicode, MS Gothic, MS Mincho, MS PGothic, MS PMincho, MS Reference Sans Serif, MS UI Gothic, MV Boli, Magneto, Malgun Gothic, Mangal, Matura MT Script Capitals, Meiryo UI, Meiryo, Microsoft Himalaya, Microsoft JhengHei, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Sans Serif, Microsoft Tai Le, Microsoft Uighur, Microsoft YaHei, Microsoft Yi Baiti, MingLiU, MingLiU-ExtB, MingLiU_HKSCS, MingLiU_HKSCS-ExtB, Miriam Fixed, Miriam, Mongolian Baiti, MoolBoran, NSimSun, Narkisim, Niagara Solid, Nyala, PMingLiU, PMingLiU-ExtB, Palace Script MT, Palatino Linotype, Papyrus, Perpetua, Plantagenet Cherokee, Playbill, Raavi, Rockwell, Rod, Sakkal Majalla, Segoe Print, Segoe Script, Segoe UI Light, Segoe UI Semibold, Segoe UI Symbol, Segoe UI, Shonar Bangla, Showcard Gothic, Shruti, SimHei, SimSun, SimSun-ExtB, Simplified Arabic Fixed, Simplified Arabic, Snap ITC, Sylfaen, Symbol, Tahoma, Times New Roman, Traditional Arabic, Trebuchet MS, Tunga, Utsaah, Vani, Verdana, Vijaya, Vladimir Script, Vrinda, Webdings, Wide Latin, Wingdings
* Languages : en-US
* Mime Types : Widevine Content Decryption Module, , Shockwave Flash, FutureSplash Player, /Native Client Executable, Portable Native Client Executable, Portable Document Format
* OS : Windows
* OS Version : 8.1
Plugins : Widevine Content Decryption Module, Chrome PDF Viewer, Shockwave Flash, Native Client, Chrome PDF Viewer
Screen Print : Current Resolution: 1366x768, Avaiable Resolution: 1366x728, Color Depth: 24, Device XDPI: undefined, Device YDPI: undefined
Silverlight Version : 
Software Version : ClientJS 0.1.5

Finger Print  : 1189623384

**Comment by jackspirou** [comment]
@muhammad009 if both systems are getting identical values, it would make sense the fingerprint id would also be identical.  There is no random salt or anything like that applied to the fingerprint, it is only based on the provided data points. 

So my next question to ask is: are the values you provided above are correct for each machine? or is some value incorrect such as `OS` or `Languages`? If the values are correct and exactly the same on both machines, then do have an additional datapoint you could use to differentiate the machines?  If you do you could use `getCustomFingerprint()` method.

**Comment by muhammad009** [comment]
Thanks Jacks fro your prompt reply, actually I have dry run the code on different machines and getting same data every time, I'm unable to find uniqueness of the fingerprint, would appreciate if you could please help me to find unique identifier.

**Comment by muhammad009** [comment]
@jackspirou Can you help me to sort out this issue?

**Comment by jackspirou** [comment]
@muhammad009 i'm not sure how much I can help you if both systems and their browsers are identical, but here are some quick ideas to uniquely identify a browser on a network.  Please note though that trying something like this will make your uniquely generated ID change as the location of the device changes:

- If you can attain the IP address (or better yet MAC address of the machine) use that
- If both machines are using different network gateways, use the IP address of the gateway
