### ISSUE TITLE
getCustomFingerprint doesn't calculate last parameter

### ISSUE THREAD

**Issue by lehaBay** [jackspirou/clientjs#19]
so, if i try to calculate like

getCustomFingerprint('dfds')

result will be the same for any string, but if do something like

getCustomFingerprint('dfds', '')

then it will actually work fine for first parameter, but last one can be anything and result will not change

**Comment by dsmontoya** [comment]
I hope this could help.

**Comment by jackspirou** [comment]
Fixed by #20
