### ISSUE TITLE
Remove Google JavaScript Compiler.jar

### ISSUE THREAD

**Issue by jackspirou** [jackspirou/clientjs#27]
Remove Minification Bash Script That Uses Google JavaScript Compiler.jar

**Comment by jackspirou** [comment]
Still using the google javascript closure compiler, but it is hidden now.  It is wrapped around a gulp plugin :)

**Comment by dsmontoya** [comment]
Why didn't you use Uglify2 instead?

**Comment by jackspirou** [comment]
@dsmontoya I started with `Uglify2` or [gulp-minify](https://github.com/hustxiaoc/gulp-minify), but there were a few issues:

* minifiying multiple files to a single file was not intuitive and needed `gulp-concat`. 
* a copy of the original source was also placed in the `dist` folder (never figured out what options existed or how they worked to remove it) which might be good behavior, but we haven't discussed it.
* The final resulting single concatenated minified file had issues and seemed broke methods like `getFlashVersion()`. 

The single pro side was that the minification was slightly better than the google closure compiler.

Since we currently are using the google closure compiler I decided it would be fine to stick with it for now until we can resolve the issues above with [gulp-minify](https://github.com/hustxiaoc/gulp-minify).  Also the resources we were able to find for the google closure compiler allowed for easy use with `Gulp`: 

* https://developers.google.com/closure/compiler/?hl=en
* https://github.com/google/closure-compiler
* https://www.npmjs.com/package/google-closure-compiler
* https://www.npmjs.com/package/closurecompiler
* https://www.npmjs.com/package/gulp-closure-compiler
* https://en.wikipedia.org/wiki/Google_Closure_Tools

All that said, if we later could figure out how to get `Uglify2` working properly, and it gets us better compression/minification I think we should switch to it immediately :)
