### ISSUE TITLE
older IEs and canvas methods

### ISSUE THREAD

**Issue by ammurphy** [jackspirou/clientjs#3]
canvas methods do not fail gracefully for IE versions 8 and below (and perhaps other browsers).

As a result, `client.getFingerprint()` will throw an error on these browsers and no fingerprint can be computed.

This can be cleared up by wrapping canvas methods in try/catch blocks, but not sure this is the method jackspirou prefers.  If so, I can submit a pull request.

**Comment by jackspirou** [comment]
@ammurphy it would be nice to first check if the current IE version supports canvas methods and then wrap the canvas methods in a try/catch.  Please submit a pull request!
