### ISSUE TITLE
Error on initilization

### ISSUE THREAD

**Issue by tallam85** [jackspirou/clientjs#55]
Hi Team,
<!DOCTYPE html>
<html>
<head>
<title> Finger Print Test</title>
</head>
<script type="text/javascript" src="https://rawgit.com/jackspirou/clientjs/master/dist/client.min.js"></script>
 <script>
 var client = new ClientJS();
 console.log("clientjs>>>>>>", client);
 </script>
</html>
for above code am getting below error, please let me am I missed any thing. Waiting for reply.

client.min.js:39 Uncaught TypeError: Cannot read property 'appendChild' of undefined

**Comment by tallam85** [comment]
Can any one please update about this issue.

**Comment by dsmontoya** [comment]
I think that's because the script runs before the body is ready

**Comment by xnet87** [comment]
u have to make to script load in the end of the page

**Comment by tallam85** [comment]
Its working now thanks @dsmontoya
