### ISSUE TITLE
Make the library ES6 compatible

### ISSUE THREAD

**Issue by juliamaksimchik** [jackspirou/clientjs#61]
Hi, 

I've tried to import the library to my application `import ClientJS from 'clientjs';` and got an error
<code>TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them</code> [here](https://github.com/jackspirou/clientjs/blob/master/src/vendor/swfobject.js#L115)

using babel-loader v6.2.5, webpack v1.13.0, clientjs v0.1.11

After some reading  I've come to conclusion that the core reason of the problem is that ES6 modules are automatically strict-mode code. (arguments.callee is forbidden to use in strict mode).

My assumption how to fix it: to update swfobject tool to the latest version where the problem won't exist.

Do you think it's all right to do it ? or Am I missing something that doesn't require this fix?

Thanks in advance.

**Comment by weisjohn** [comment]
@juliamaksimchik you closed this, did you find a resolution to it?

**Comment by bdkent** [comment]
Any updates here? I am unable to use this with Browserify...

**Comment by Remigius2011** [comment]
Sorry to say, but I've left ClientJS frustrated - I wasn't able to get it to run successfully in a webpack/ES6 setting (although the lib would be very helpful!)

**Comment by sasivarnan** [comment]
Anyone found an workaround for this ?
I am also facing this issue in my TypeScript codebase.

**Comment by Lavos96** [comment]
https://github.com/jackspirou/clientjs/issues/111

**Comment by BendingBender** [comment]
Yes, see #108.
