### ISSUE TITLE
Using clientjs in cordova app

### ISSUE THREAD

**Issue by atgillette** [jackspirou/clientjs#64]
Hi,

I'm trying to get clientjs to run in my cordova app.  But `getFingerprint()` is undefined and only the following methods are available:

```
getBrowser: function()

getCPU: function()

getDevice: function()

getEngine: function()

getOS: function()

getResult: function()

getUA: function()

setUA: function(a)
```

**Comment by marcusbesjes** [comment]
Same issue here, just trying to use it in a "normal" module based web app

```JavaScript
'use strict'

const ClientJS = require('clientjs')

// Create a new ClientJS object
const client = new ClientJS()
console.log('wat is this client', client)

// Get the client's fingerprint id
var fingerprint = client.getFingerprint() // << throws

// Print the 32bit hash id to the console
console.log(fingerprint)
```

results in 

![image](https://cloud.githubusercontent.com/assets/3897729/24967712/4fde6194-1fab-11e7-918a-945903310101.png)

**Comment by AnimaLupi** [comment]
Same here. Seeing the issue was opened on 16 Oct 2016, I guess this library is dead (by also looking at last commit). Too bad :-(
