### ISSUE TITLE
Client doesn't return any device details

### ISSUE THREAD

**Issue by Harshit369** [jackspirou/clientjs#65]
```
    var UA = new ClientJS();
var ua = UA.getBrowserData().ua;
var canvasPrint = UA.getCanvasPrint();
return {
    "device_type": UA.getDevice(),                        //returns undefined
    "model": UA.getDeviceType(),                          //returns undefined
    "manufacturer": UA.getDeviceVendor(),           //returns undefined 
    'fingerprint':UA.getCustomFingerprint(ua, canvasPrint)
}
```

**Comment by prashathsenthil** [comment]
@Harshit369 any updates on this? me too facing the same issue with getDevice(), returns undefined...

**Comment by EliasS87** [comment]
It appears that it is the UAParser Library ClientJS uses to get the browserData is failing, or according to the last comment on [this](https://github.com/faisalman/ua-parser-js/issues/224) issue on the UAParser github, it does not actually detect Desktops.
