### ISSUE TITLE
Flash Plugin warning

### ISSUE THREAD

**Issue by clarkeash** [jackspirou/clientjs#68]
I get this appear in chrome:

<img width="323" alt="screen shot 2017-02-15 at 15 27 22" src="https://cloud.githubusercontent.com/assets/1612186/22978545/700635e4-f393-11e6-9787-ccd30a5379c9.png">

I am using clientjs to get the browser information (i dont particularly care about if they have flash enabled) Is there anything I can do stop this appearing (doesnt look good to the users)?

Browser: Chrome
Version: 56
OS: MacOS Sierra 10.12.3

**Comment by andymilsted** [comment]
+1

**Comment by ben182** [comment]
Same

**Comment by The-Don-Himself** [comment]
Awesome plugin, but this issue is a potential deal breaker.

**Comment by doonfrs** [comment]
+1

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0). Feel free to reopen this ticket if you still have problems.
