### ISSUE TITLE
Issue in using clientjs with angular2

### ISSUE THREAD

**Issue by arunsivan** [jackspirou/clientjs#70]
is it possible to integrate it with angular2.  I am unable to import clientjs as a module.

**Comment by martinvondracek** [comment]
@arunsivan in react I am using it this way

import it in your component this way

`import 'clientjs';`

and then you can use it standard way as it is in docs

`new ClientJS().isMobile();`

**Comment by 1ambda** [comment]
@arunsivan I am using this library with angular2.

I added a custom type def into my `custom-typings.d` referenced by [tsconfig.js](https://stackoverflow.com/questions/38971984/how-to-add-custom-typings-in-typescript-2-0)

```
// custom-typings.d
declare let ClientJS: any;

// use in a .ts file
import 'clientjs'

...
    const client = new ClientJS();
...
```

**Comment by BendingBender** [comment]
Type definitions are now available from DefinitelyTyped: https://www.npmjs.com/package/@types/clientjs
