### ISSUE TITLE
Karma Error

### ISSUE THREAD

**Issue by Mkhonto3** [jackspirou/clientjs#72]
Hi guys 

I am getting Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 0 of 0 ERROR (0.006 secs / 0 secs) error when starting my karma, not sure why because I am starting it in the right directory. Any help!
![screen shot 2017-05-04 at 12 54 01 pm](https://cloud.githubusercontent.com/assets/17846314/25700639/d5c09b50-30c8-11e7-8a2a-377f15e1b199.png)

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0). Feel free to reopen this ticket if you still have problems.
