### ISSUE TITLE
Flash plugin flickers on screen

### ISSUE THREAD

**Issue by jon-node28** [jackspirou/clientjs#74]
When getting client plugins a flash plugin window briefly flickers onscreen. This is with flash disabled.

**Comment by xcorter** [comment]
+1

**Comment by valentyn-hrynevich** [comment]
+1
Please, can you fix this problem?

**Comment by MarkOdey** [comment]
Yes I got the same problem too and would like to find a solution.

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0). Feel free to reopen this ticket if you still have problems.
