### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by lanling1213** [jackspirou/clientjs#76]
when i include this js file client.js ,then go on the mistakes,please tell me why and how to slove the problem!!
thinks you very much!!

**Comment by codethebeard** [comment]
I'm having the same exact issue.

**Comment by BatshevaAmor** [comment]
It happened to me too.
I solved it by including the
'deployJava.js', 'fontdetect.js', 'murmurhash3.js', 'swfobject.js' and 'ua-parser.js' files [https://github.com/jackspirou/clientjs/tree/master/src/vendor]
before 'client.js'
