### ISSUE TITLE
Duplicate fingerprint for multiple chrome browser

### ISSUE THREAD

**Issue by gauravc-cuelogic** [jackspirou/clientjs#77]
Hi,
I'am getting same fingerprint from multiple chrome browsers running on this Version 59.0.3071.115 (Official Build) (64-bit) on windows 10 OS. The machines are located on different locations. common fingerprint which is generated is `2451595692`, I'am using getCustomFingerprint() Method for generating fingerprint.

Please Advice.

**Comment by aarvee11** [comment]
You must be using parameters which are not client specific rather global like user-agent, os etc in order to generate the Custom Fingerprint. Please use parameters which could be unique or a combination of parameters that could be unique to users. Then there will be less collisions

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0) and reopen this issue when you still have problems.
