### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Infeligo** [jackspirou/clientjs#8]
Have use considered publishing ClientJS to npm? As per npm's [blog](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging), it is totally acceptable for a package to be solely client side. Npm repo is supported by tools other than Bower. For example, [jspm](http://jspm.io/) is an alternative to Bower and can resolve packages from npm repo.

**Comment by jackspirou** [comment]
I'll close this issue, but feedback would be appreciated since I have never published to npm before. 

https://www.npmjs.com/package/clientjs
