### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by BrandonCopley** [jackspirou/clientjs#83]
This project appears to be unmaintained - What projects should we be looking at using in the future?

**Comment by WuglyakBolgoink** [comment]
good question....

**Comment by ryuken** [comment]
some kind of alternative: https://github.com/Valve/fingerprintjs2

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0). Feel free to reopen this ticket if you still have problems.
