### ISSUE TITLE
Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by solsticedhiver** [jackspirou/clientjs#84]
I got this when I only use `<script>static/js/client.min.js</script>` (github version)

    VM226 client.min.js:39 
    Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at new Detector (VM226 client.min.js:39)
    at new p (VM226 client.min.js:1)

**Comment by nx269** [comment]
Place script tag in body
