### ISSUE TITLE
getTimeZone not consistent across browsers

### ISSUE THREAD

**Issue by dabl62** [jackspirou/clientjs#86]
The string returned from getTimeZone() is not consistent across different browsers.

Chrome, Firefox and Safari return "BST"
IE11 and Edge return "GMT Daylight Time"

**Comment by BendingBender** [comment]
Please try out the new release (https://github.com/jackspirou/clientjs/releases/tag/v0.2.0). Feel free to reopen this ticket if you still have problems.
