### ISSUE TITLE
use in vue not enough methods?

### ISSUE THREAD

**Issue by sevilen** [jackspirou/clientjs#91]
npm install clientjs

import in component
..
import ClientJS from 'clientjs'

const client = new ClientJS()

console.log(client) // just have a few methods
![image](https://user-images.githubusercontent.com/30746521/43637198-ee34a56a-9746-11e8-8eb4-a9f943016b51.png)

**Comment by juntan86** [comment]
Did you figure out how to fix that?

**Comment by ReevesOvO** [comment]
@juntan86 
use this case：
import 'clientjs'

.....

// use
// if you use eslint or tslint, you should ignore the next line
if (new ClientJS().isMobile()) {
    // dosomething...
}

**Comment by linkshady** [comment]
@sevilen  tried it, it isnt working for me in my react nextjs project
