### ISSUE TITLE
isJava() returns different results following web browsers.

### ISSUE THREAD

**Issue by MisooKim** [jackspirou/clientjs#92]
Hello.
I tested the clientJS.

In my knowledge, 'isJava()' function returns the whether Java is installed in client pc.
In chrome, the function returned 'FALSE', 
but, in explorer, the function returned 'TRUE'.

Do I misunderstanding this function?

**Comment by BendingBender** [comment]
This function only reports the availability of the Java plugin in the current browser. Nowadays, most browsers have completely disabled all means to add plugins so this functionality shouldn't be used any more.
