### ISSUE TITLE
I am unable to import clientjs as a module.

### ISSUE THREAD

**Issue by chetan2609** [jackspirou/clientjs#93]
is it possible to integrate it with angular2. I am unable to import clientjs as a module.

I have followed below steps,

==> installed it
 npm install clientjs

==> added in angular.json
 "scripts": [
              "node_modules/clientjs/dist/client.min.js"
  ]

==> import it in my component this way
import 'clientjs';

==> declare it 
let ClientJS: any;

==> and used it
var client = new ClientJS();
var device = client.getDevice();

but not working gives error 
core.js:15713 ERROR Error: Uncaught (in promise): TypeError: ClientJS is not a constructor

Can someone please help me out?

**Comment by dmisdm** [comment]
have you tried using it it like:
```js
import ClientJS from 'clientjs'
const client = new ClientJS();
```

**Comment by chetan2609** [comment]
thanks for your support.
it's working fine now

**Comment by etochesnok** [comment]
closed.
